### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by satishchhatpar** [IBM/BlockchainNetwork-CompositeJourney#22]
Getting error  after  running  createPeerAdminCard.sh

/Users/satishchhatpar/node-v6.10.0-darwin-x64/lib/node_modules/composer-cli/node_modules/composer-common/lib/cardstore/businessnetworkcardstore.js:54
    async get(cardName) {
          ^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/satishchhatpar/node-v6.10.0-darwin-x64/lib/node_modules/composer-cli/node_modules/composer-common/index.js:56:43)
    at Module._compile (module.js:570:32)
/Users/satishchhatpar/node-v6.10.0-darwin-x64/lib/node_modules/composer-cli/node_modules/composer-common/lib/cardstore/businessnetworkcardstore.js:54
    async get(cardName) {
          ^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/satishchhatpar/node-v6.10.0-darwin-x64/lib/node_modules/composer-cli/node_modules/composer-common/index.js:56:43)
    at Module._compile (module.js:570:32)
Using composer-cli at
/Users/satishchhatpar/node-v6.10.0-darwin-x64/lib/node_modules/composer-cli/node_modules/composer-common/lib/cardstore/businessnetworkcardstore.js:54
    async get(cardName) {
          ^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/satishchhatpar/node-v6.10.0-darwin-x64/lib/node_modules/composer-cli/node_modules/composer-common/index.js:56:43)
    at Module._compile (module.js:570:32)

**Comment by ljbennett62** [comment]
@satishchhatpar - so I just went through the pattern and did not run into the same error. My questions to you are:
1) Did you install the pre-reqs:
- Dockerv1.13
- npm V5.6.0 or higher
- nvm 8.11.3 (use npm to install node)
- node 8.11.3 or higher
- composer-cli@.19.5

I have found that if you don't have the right version of node - it creates problems.

**Comment by ljbennett62** [comment]
more info: You will need to uninstall composer, upgrade to node 8.9 and re-install composer. The reason is that composer depends on fabric node-sdk which depends on grpc. grpc is sensitive to the level of node you use, so by just upgrading node and not re-installing composer the version of grpc currently installed will not be the right one for node, so then you get the error you described.
